---
# tasks file for flask-auth-example

- name: Start system setup
  ansible.builtin.import_tasks: setup_system.yml

- name: Start application in a system
  ansible.builtin.import_tasks: system_app.yml
  when: not docker

- name: Start application in Docker
  ansible.builtin.import_tasks: docker_app.yml
  when: docker

- name: Enable firewall
  ansible.builtin.import_tasks: firewall.yml
